### ISSUE TITLE
Get assets for map view

### ISSUE THREAD

**Issue by MadejaMaciej** [niner-games/game-react-lost-dutchman-mine#24]
@trejder could you crop out small parts of the map, so I can place it randomly? I have 3 mountains, city and cactus cropped out already, so everything else what will come

**Comment by trejder** [comment]
@MadejaMaciej Please, remember that in this version of the game we are using a **static, non-generated map**. So you only need a whole map as an image (to be provided) plus a pieces of map during evening and night to calculate correct filter.

You don't need small single map parts. I have just checked that in every game and every save map is the same.

**Comment by MadejaMaciej** [comment]
Okay, thank you!

**Comment by mrfatguy** [comment]
@MadejaMaciej Map [provided to Wiki](https://github.com/niner-games/game-react-lost-dutchman-mine/wiki/Resources.-Environment.-Map#entire-map).
