### ISSUE TITLE
Extract player character sprite's animation

### ISSUE THREAD

**Issue by MadejaMaciej** [niner-games/game-react-lost-dutchman-mine#25]
@trejder could you crop out player for me to use, with all frames of animations?

**Comment by trejder** [comment]
Player's animation in town added to [resources section of Wiki](https://github.com/niner-games/game-react-lost-dutchman-mine/wiki/Resources.-Environment.-Prospector#city) and sent via email.

I am closing this ticket, as player's animation in any other situations will be provided in separate tickets.

**Comment by trejder** [comment]
Please, keep in mind that .zip files intentionally contains multiplications of each step or move sequence. Captured like that in case it would be easier for you to crop it from other part of animation.

I roughly estimate that each move (left, right, up, down) consists of no more than 3-5 frames.

**Comment by MadejaMaciej** [comment]
Oh okay, got it now - it should be easier than I thought then!
