### ISSUE TITLE
Crop out buildings from the city to use

### ISSUE THREAD

**Issue by MadejaMaciej** [niner-games/game-react-lost-dutchman-mine#26]
@trejder could you crop out all buildings in the village, except assay office and mercantile?

**Comment by MadejaMaciej** [comment]
@trejder  I received Assay office and mercantile - could you crop out rest of the building and send me an email with them?

**Comment by trejder** [comment]
@MadejaMaciej Building by day + panorama [provided in Wiki](https://github.com/niner-games/game-react-lost-dutchman-mine/wiki/Resources.-Town) and over email.

**Comment by MadejaMaciej** [comment]
I would rather use shader for night, instead of croping it once again. So I think for now there is no need to do that.

**Comment by trejder** [comment]
Sure thing, closing then.
