### ISSUE TITLE
Prepare initial translation system

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/game-react-lost-dutchman-mine#27]
# Overview

Prepare necessary code / engine and translation files to support game texts in seven language:

- English (default language and base for all translations)
- Polish
- German
- Spanish
- French
- Ukrainian
- Silesian

## Narrative

- **As a** player
- **I want** to see game in my local language
- **To** be more convinced into purchasing paid version in future

## Acceptance Criteria

- **Given** that a game is started
- **When** I select some language
- **And** and that language is not _English_ (not _Latin_ character set)
- **Then** I see all in-game texts translated
- **And** all the language-specific characters are correctly displayed

## Details

All translations will be provided by @trejder or @BeataTrej. Some of them will be:

- manually translated (Polish, English),
- auto-translated ([Google Translate](https://translate.google.com/), [Sillin Translatōr](https://silling.org/translator/?dir=pol-szl#translation)) and corrected by a person speaking in that language (French, Spanish)
- auto-translated and left as is, as we don't know nobody speaking in that language (Ukrainian, Silesian)*

Note: A lot of people speaks Silesian. But we need a _professional translation_, i.e. with usage of correct diacritics (see below).

## Languages and characters set

Please, double check that game supports all languages and are national-specific characters in that languages correctly.

### The Latin alphabet

(for reference)

`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`, `l`, `m`, `n`, `o`, `p`, `q`, `r`, `s`, `t`, `u`, `w`, `v`, `x`, `y`, `z`
`A`, `B`, `C`, `D`, `E`, `F`, `G`, `H`, `I`, `J`, `K`, `L`, `M`, `N`, `O`, `P`, `Q`, `R`, `S`, `T`, `U`, `W`, `V`, `X`, `Y`, `Z`

Link to Wikipedia: [Latin script](https://en.wikipedia.org/wiki/Latin_script)

### The Polish alphabet

(specific characters only + entire Latin)

`ą`, `ć`, `ę`, `ł`, `ń`, `ó`, `ś`, `ż`, `ź`
`Ą`, `Ć`, `Ę`, `Ł`, `Ń`, `Ó`, `Ś`, `Ż`, `Ź`

Link to Wikipedia: [Polish language](https://en.wikipedia.org/wiki/Polish_language)

### German alphabet

(specific characters only + entire Latin)

`ä`, `ß`, `ö`, `ü`
`Ä`, `ẞ`, `Ö`, `Ü`

Link to Wikipedia: [German alphabet](https://en.wikipedia.org/wiki/German_alphabet)

### The Spanish alphabet

(specific character sonly + entire Latin)

`¿`, `¡`, `á`, `é`, `í`, `ó`, `ú`, `ñ`
`¿`, `¡`, `Á`, `É`, `Í`, `Ó`, `Ú`, `Ñ`

Link to Wikipedia: [Spanish orthography](https://en.wikipedia.org/wiki/Spanish_orthography)

### The French alphabet

(specific characters only + entire Latin)

`à`, `â`, `æ`, `ç`, `é`, `è`, `ê`, `ë`, `î`, `ï`, `ô`, `œ`, `ù`, `û`, `ü`, `ÿ`
`À`, `Â`, `Æ`, `Ç`, `É`, `È`, `Ê`, `Ë`, `Î`, `Ï`, `Ô`, `Œ`, `Ù`, `Û`, `Ü`, `Ÿ`

Link to Wikipedia: [French orthography](https://en.wikipedia.org/wiki/French_orthography#Alphabet)

### The Silesian alphabet

(specific characters only + entire Polish + entire Latin)

`ã`, `ẽ`, `ŏ`, `ō`, `ô`, `õ`, `ů`
`Ã`, `Ẽ`, `Ŏ`, `Ō`, `Ô`, `Õ`, `Ů`

Link to Wikipedia: [Silesian language](https://en.wikipedia.org/wiki/Silesian_language)

### The Ukrainian alphabet

(Cyrylic)

`а`, `б`, `в`, `г`, `ґ`, `д`, `е`, `є`, `ж`, `з`, `и`, `і`, `ї`, `й`, `к`, `л`, `м`, `н`, `о`, `п`, `р`, `с`, `т`, `у`, `ф`, `х`, `ц`, `ч`, `ш`, `щ`, `ь`, `ю`, `я`, `'`
`А`, `Б`, `В`, `Г`, `Ґ`, `Д`, `Е`, `Є`, `Ж`, `З`, `И`, `І`, `Ї`, `Й`, `К`, `Л`, `М`, `Н`, `О`, `П`, `Р`, `С`, `Т`, `У`, `Ф`, `Х`, `Ц`, `Ч`, `Ш`, `Щ`, `Ь`, `Ю`, `Я`, `'`

Link to Wikipedia: [Ukrainian alphabet](https://en.wikipedia.org/wiki/Ukrainian_alphabet#Letter_names_and_pronunciation)

### All required characters

(for testing purposes)

    ąćęłńóśżźĄĆĘŁŃÓŚŻŹäßöüÄẞÖÜ¿¡áéíóúñ¿¡ÁÉÍÓÚÑ
    àâæçéèêëîïôœùûüÿÀÂÆÇÉÈÊËÎÏÔŒÙÛÜŸãẽŏōôõůÃẼŎŌÔÕŮ
    абвгґдеєжзиіїйклмнопрстуфхцчшщьюяАБВГҐДЕЄЖЗИІЇЙКЛМНОПРСТУФХЦЧШЩЬЮЯ'
    abcdefghijklmnopqrstuwvxyzABCDEFGHIJKLMNOPQRSTUWVXYZ

All the tests and checks should be preformed using both in-game font (#22) and the standard, default mobile app font.

**Comment by mrfatguy** [comment]
@MadejaMaciej Please, provide some technical details on how to perform translations -- here or in the email.

I will put it into our Wiki and only then we will close this ticket, OK?

**Comment by MadejaMaciej** [comment]
@mrfatguy The best would be to just provide a file with every possible string and it's translation (and with a place, where this string is displayed). Then I can move it over without any problems. 

I'll open new ticket for creating that file, with a name "Create file with every possible in game string and it's translation" so we can close this one.
