### ISSUE TITLE
Remember user selection about in-game language

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/game-react-lost-dutchman-mine#49]
## Overview

Please, implement app-wide flag or player's profile setting that will store language that use has currently selected.

When application is started next time, remembered language should be used and entire interface should be in that language.

## Narrative

- **As a** player
- **I want** my preference about language to be saved
- **So that** I don't have to change game's language to preferred one each time

### Save language

- **Given that** I have started a game
- **And that** I am in the options screen
- **When** I change current in-game language
- **Then** my preference is remembered

### Load language

- **Given that** I have started a game
- **When** I pass the logo screen
- **Then** I can see that the entire game is in language that I have set or used previously

**Comment by MadejaMaciej** [comment]
That is already done, closing
